FROM node:22

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

#Variables de entorno para habilitar el polling
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
